language: python

python:
 - "2.7"
 - "3.5"
 - "3.6"
 - "3.7-dev"

services:
 - mysql

notifications:
  email:
    - rfkelly@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#services-dev"
    use_notice: false
    skip_join: false

before_install:
  # https://github.com/travis-ci/travis-ci/issues/7940
  - sudo rm -f /etc/boto.cfg

install:
  - make install-dev

before_script:
  - mysql -e 'create database tokenserver_test;'

script:
  - make flake8
  - export BOTO_CONFIG=/dev/null # https://github.com/travis-ci/travis-ci/issues/7940
  - MOZSVC_SQLURI=pymysql://root@localhost/tokenserver_test make tests
  - make tests
